### ISSUE TITLE
Improving Client Tests

### ISSUE THREAD

**Issue by vigneshwara044** [maidsafe/safe_app_java#72]
The following scenarios will be added.

Scenario
- copy the log.toml file and safe-core.config file with unlimited mutations to a folder.
- use getAppStem and fetch the expected name for the app’s executable without extension. 
- set the additional search paths and initialize logging.
- create a session and set up the app container.
- perform some mutations.
- get the mDataInfo and perform some operations.
- get the account info and verify if puts have exceeded 1000.
- Verify if the output log file exists.
- getAppContainerName and verify.
- resetObjectCache and check the contents of permission handle and entries handle.
- refreshAccessInfo and fetch the previously accessible containers and verify that are not accessible.

Scenario
- Create a session
- Create, encode and send a container request to the authenticator with additional permissions.
- Get the containerMdInfo for the additional container and perform some operations.

**Comment by S-Coyle** [comment]
Confirmed with @vigneshwara044 this does not require QA
