### ISSUE TITLE
Improving Immutable Data Test

### ISSUE THREAD

**Issue by vigneshwara044** [maidsafe/safe_app_java#74]
Deprecate getSerialised API.

**Comment by vigneshwara044** [comment]
Closed for now as `getSerialisedSize` is not being removed.

**Comment by lionel1704** [comment]
If the API is not being deprecated, we need to understand the use case, and demonstrate it in our unit test cases. Reopening this.

**Comment by lionel1704** [comment]
Resolved in #87

**Comment by S-Coyle** [comment]
Confirmed with @vigneshwara044 this does not require QA
